export const GET_POINTS_SUCCESS = 'GET_POINTS_SUCCESS';
export const PUT_POINTS_SUCCESS = 'PUT_POINTS_SUCCESS';
export const DELETE_POINTS_SUCCESS = 'DELETE_POINTS_SUCCESS';

export const GET_LISTS_SUCCESS = 'GET_LISTS_SUCCESS';
export const POST_LIST_SUCCESS = 'POST_LIST_SUCCESS';
export const DELETE_LIST_SUCCESS = 'DELETE_LIST_SUCCESS';

export const GET_SQUARES_SUCCESS = 'GET_SQUARES_SUCCESS';

export const BEGIN_API_CALL = 'BEGIN_API_CALL';
export const API_CALL_ERROR = 'API_CALL_ERROR';

export const SQUARES_PAGE_SIZE_CHANGE = 'SQUARES_PAGE_SIZE_CHANGE';
export const POINTS_PAGE_SIZE_CHANGE = 'POINTS_PAGE_SIZE_CHANGE';
export const SQUARES_PAGE_CHANGE = 'SQUARES_PAGE_CHANGE';
export const POINTS_PAGE_CHANGE = 'POINTS_PAGE_CHANGE';
